CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    profile_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    icon VARCHAR(255)
); 